baseURL = "https://containersolutions.github.io/runbooks/"
languageCode = "en-us"
title = "Runbooks"
theme = ["hugo-debugprint", "hugo-primer-cs"]

disqusShortname = "runbooks"
enableGitInfo = "true"

googleAnalytics = "G-1MRFR0S0VT"

[privacy.googleAnalytics]
respectDoNotTrack = true

[params]
showFooterCredits = false

[frontmatter]
date = [":git", "lastmod", "date", "publishDate"]

[menu]

[[menu.main]]
name = "Nav Menu"
weight = 10
identifier = "navmenu"
url = "/"

[[menu.main]]
name = "Home"
parent = "navmenu"
weight = 20
identifier = "home"
url = "/"
permalink = "/"
hide = true

[[menu.main]]
name = "Kubernetes"
parent = "navmenu"
weight = 30
identifier = "kubernetes"
url = "/posts/kubernetes/"
permalink = "/posts/kubernetes"

[[menu.main]]
name = "Linux"
parent = "navmenu"
weight = 40
identifier = "linux"
url = "/posts/linux/"
permalink = "/posts/linux"

[[menu.main]]
name = "Networking"
parent = "navmenu"
weight = 50
identifier = "networking"
url = "/posts/networking/"
permalink = "/posts/networking"

[[menu.main]]
name = "Python"
parent = "navmenu"
weight = 60
identifier = "python"
url = "/posts/python/"
permalink = "/posts/python"

[[menu.main]]
name = "How-Tos"
parent = "navmenu"
weight = 70
identifier = "how-to"
url = "/posts/how-to/"
permalink = "/posts/how-to"
